server {
    listen 443 ssl;
    server_name noticias360-grupoN.lab.umng.edu.co;
    ssl_certificate     /etc/letsencrypt/live/noticias360-grupoN.lab.umng.edu.co/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/noticias360-grupoN.lab.umng.edu.co/privkey.pem;
    # TODO Parcial 3.1: agregar headers de seguridad
    root /var/www/noticias360/dist/noticias360-frontend;
    index index.html;
    location / { try_files $uri $uri/ /index.html; }
    location /api/ {
        proxy_pass http://10.0.0.11:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
